### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by revilationer** [MBach/LeMondeRssReader#6]
Hi
I just saw your app and if you need a new logo or widget design i can help you
I am waiting for you reply

**Comment by MBach** [comment]
Hello @revilationer 
Thank you for offering your help! Currently, I don't have much widgets in this App, but I need help for transitions. It's not very smooth when you're opening an article from the Home Page. Some work need to be done on this area. About the logo, why not, because I'm reusing the logo from the website, and it's not open source, so it might be a good idea to have a new one.
